graph1:
  title: Graph One
  short_description: This is the short description.
  long_description: Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  type: Line graph
  author: J
  last_updated: mm/dd/yy
